-- ============================================
-- PHASE 4: AGGREGATE TABLES FOR ANALYTICS
-- ============================================
-- Purpose: Pre-calculated summaries for business intelligence
-- Created: November 5, 2025
-- Author: Abhiiram
-- ============================================
-- 1. CUSTOMER SUMMARY
-- 2. PRODUCT SUMMARY
-- 3. DAILY SALES SUMMARY
-- 4. MONTHLY SALES SUMMARY
-- [Use all the SQL you already ran successfully]